### PR TITLE
Add Readyset MySQL blog feed

### PR DESCRIPTION
**Pull request by altmannmarcelo**
Add Readyset MySQL feed to planet.ini

### CODE REVIEW

**Comment by jfg956** [comment]
Thanks for this PR Marcelo.  I see you aggregate the MySQL Tag Feed, what would you think about aggregating a filtered feed instead ?  This would allow to match more posts, including {1}.  Suggestion below for a modified PR (I will let you change this yourself so you stay a contributor to the repo).  Cheers, J-F

{1}: https://blog.readyset.io/optimizing-performance-a-2024-updated-guide-to-setting-up-caching-in-laravel/

```
# Needs to end with _filtered for filtering icon.
[com_readyset_filtered]
  # Original feed: https://blog.readyset.io/rss/
  # Too much non-MySQL content on original feed, so filtered via siftrss.
  # Configuration: include / content:encoded / match regex / /mysql|mariadb/i.
  title = Readyset Blog - MySQL Track
  link = https://blog.readyset.io/
  feed = https://siftrss.com/f/YKqo1wd3l1Q
  twitter = readysetio
```

**Comment by altmannmarcelo** [comment]
@jfg956 thanks for suggesting the filtering. Adjusted and force-pushed the changes.

**Comment by jfg956** [comment]
Merged, thanks for the PR.

And FYI, I did this minor change.
https://github.com/oursqlcommunity-org/planet/commit/40562559dcde28e4b57edbd0505c21e53df4b12f

**Comment by jfg956** [comment]
FYI, I tweeted about this.
https://twitter.com/jfg956/status/1773384711542321372

**Pull request merged**
